@startuml

package "Graph" {
  node "Variables" {
      () "x1"
      () "x2"
      () "x3"
      () "……"
    }

  node "EdgeList" {
      ()"X1" --> X2
      ()"X4" <-- X3
      ()"X5" <--> X6
  }
}

@enduml